'use client'

import { BookOpen, Check, CircleAlert } from 'lucide-react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'

export function DocsDialog({ open, onOpenChange, releaseNotes = false }: { open: boolean; onOpenChange: (open: boolean) => void; releaseNotes?: boolean }) {
  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-xl">
      <DialogHeader><div className="mb-3 flex items-center gap-2 text-primary"><BookOpen className="size-5" /><span className="font-mono text-xs">OBSIDIAN / v0.5.0</span></div><DialogTitle>{releaseNotes ? 'A harder target. Not a false promise.' : 'Meet your new compilation pipeline.'}</DialogTitle><DialogDescription>A Luau frontend lowers language-level syntax into a polymorphic VM; native Luau output remains available separately. No promise of unrecoverable code.</DialogDescription></DialogHeader>
      <div className="docs-body">
        <section><h3>{releaseNotes ? 'What ships in v0.5' : 'How it works'}</h3><p>Source is parsed into an AST, compiled to register bytecode, and bundled with only the VM handlers actually used by the build. Version 0.5 adds virtualized iterator loops, multiple-result semantics, strict VM-only builds, and accurate fallback diagnostics. The VM frontend supports Luau type syntax, continue, interpolation, casts, conditional expressions, bitwise operators, compound assignments, closures, multiple returns, coroutines, metatables, and generalized iteration. Six independently configurable passes transform VM builds; compatibility packages report only the passes they actually apply. Source is sent to the compiler, never executed, and is not saved by this app.</p><ol><li><strong>Packed bytecode:</strong> variable-length integer records with independent 24-bit seeds and feedback-based byte encoding. Numeric constants are encoded too.</li><li><strong>Control-flow flattening:</strong> explicit successor labels, relocated branches, and shuffled instruction storage.</li><li><strong>Polymorphic handlers:</strong> per-build opcode aliases, operand permutations, remapped registers and constants, and balanced dispatch.</li><li><strong>Lazy bounded chunk and constant decoding:</strong> separately seeded constants are decoded only when used, then cached.</li><li><strong>Runtime symbol mangling:</strong> fresh randomized VM-local identifiers on each build.</li><li><strong>Compact output:</strong> strip formatting without changing string bytes.</li></ol></section>
        <section><h3 className="flex items-center gap-2"><Check className="size-4 text-primary" /> VM-supported syntax</h3><p>Single and multiple locals, parallel assignments (including swaps and nil padding), tables and field access, arithmetic, comparisons, short-circuit logic, if / elseif / else, while, repeat / until, numeric and generic for loops (pairs, ipairs, and custom iterators), break, and do blocks. Global and local function declarations, dotted and colon-method declarations, anonymous function expressions, recursion, mutable lexical closures, callbacks, parameters, and varargs are virtualized. Final calls and varargs expand in assignments, arguments, returns, and table constructors, preserving nil holes. Parenthesized calls and varargs correctly produce a single result. Existing globals and Roblox methods are supported.</p></section>
        <section><h3 className="flex items-center gap-2"><CircleAlert className="size-4 text-primary" /> Know the boundaries</h3><p>VM mode is the protected default path. It accepts syntax supported by the bundled Luau compiler, including functions, closures, varargs, type annotations and generics, compound assignments, continue, generalized iteration, if expressions, and interpolated strings. Input and output are compiled for syntax validation without execution. Output runs directly in Roblox Script, LocalScript, or ModuleScript contexts without loadstring. Only plain quoted strings are byte-escaped; comments and horizontal spacing may be reduced. Existing escapes, long strings, interpolations, directives, line breaks, identifiers, and control flow are preserved. This is conservative source-level obfuscation, not full arbitrary VM virtualization. Roblox engine APIs and type correctness must be tested in Studio. Require VM protection rejects any syntax the Luau frontend cannot lower; protected builds never use the source-loader fallback. Legacy API callers without a mode retain their existing behavior, including an explicitly opted-in loader fallback.</p><p><strong>There is no ChatGPT-proof setting.</strong> The decoder and its state must ship with executable code. AI-assisted or manual analysis can reconstruct behavior, and an instrumented runtime can observe decoded instructions and constants. These passes are reversible obfuscation, not cryptographic encryption, authentication, or a security boundary. Keep keys, authorization decisions, and sensitive logic in server-only code.</p><p>VM execution and decoding add memory, runtime, and output-size overhead. Decoded records are cached to avoid decoding on each loop iteration. Disabling passes trades analysis resistance for simpler output. VM builds add no runtime source evaluation or network loaders. Compatibility packages do evaluate recovered source locally. Integrity checks detect accidental corruption/tampering but do not make client-side code unbreakable. Independent reverse-engineering review remains a release criterion.</p></section>
        <section><h3>Using your output</h3><ol><li>Paste a script or upload a .lua / .luau file (up to 32 KiB).</li><li>Choose your transformation passes and select Obfuscate script.</li><li>Download the generated .lua file and test it in a Roblox Studio Script or ModuleScript in the same execution context as your source.</li></ol><p>Your source, settings, and output are session-only. Download your build before leaving the page. Roblox Studio compatibility must be verified with your own script.</p></section>
      </div>
    </DialogContent>
  </Dialog>
}
